export const columns = [
  {
    title: '#',
    type: 'number',
    width: '50px',
    fixed: 'left',
  },
  {
    key: 'triggerState',
    title: '状态',
    width: '80px',
    sort: true,
    fixed: 'left',
    customSlot: 'triggerState',
  },
  {
    key: 'priority',
    title: '触发器优先级',
    width: '140px',
    align: 'center',
    fixed: 'left',
    sort: true,
    hide: true,
  },
  {
    key: 'triggerType',
    title: '触发器类型',
    width: '140px',
    align: 'center',
    fixed: 'left',
    sort: true,
    hide: true,
  },
  {
    key: 'triggerName',
    title: '触发器名称',
    align: 'center',
    sort: true,
    width: '200px',
  },
  {
    key: 'triggerGroup',
    title: '触发器组',
    align: 'center',
    sort: true,
    hide: true,
    width: '120px',
  },
  {
    key: 'triggerDescription',
    title: '触发器描述',
    width: '200px',
    ellipsisTooltip: true,
  },
  {
    key: 'jobName',
    title: '任务名',
    align: 'center',
    width: '200px',
    sort: true,
    ellipsisTooltip: true,
  },
  {
    key: 'jobGroup',
    title: '任务组',
    align: 'center',
    width: '120px',
    sort: true,
    hide: true,
    ellipsisTooltip: true,
  },
  {
    key: 'jobDescription',
    title: '任务描述',
    width: '200px',
    ellipsisTooltip: true,
  },
  {
    key: 'nextFireTime',
    title: '下次触发时间',
    align: 'center',
    width: '180px',
    ellipsisTooltip: true,
  },
  {
    key: 'prevFireTime',
    title: '上次触发时间',
    align: 'center',
    width: '180px',
    ellipsisTooltip: true,
  },
  {
    key: 'startTime',
    title: '开始时间',
    align: 'center',
    width: '180px',
    sort: true,
    ellipsisTooltip: true,
  },
  {
    key: 'endTime',
    title: '结束时间',
    align: 'center',
    width: '180px',
    sort: true,
    ellipsisTooltip: true,
  },
  {
    key: 'cron',
    title: 'cron',
    align: 'center',
    width: '180px',
  },
  {
    key: 'jobParam',
    title: '任务参数',
    width: '200px',
    ellipsisTooltip: true,
  },
  {
    key: 'jobClass',
    title: '任务执行类',
    width: '200px',
    ellipsisTooltip: true,
    customSlot: 'jobClass',
  },
  {
    key: 'jobClassName',
    title: '类路径',
    width: '400px',
    ellipsisTooltip: true,
  },
  {
    key: 'operator',
    title: '操作',
    align: 'center',
    width: '240px',
    customSlot: 'operator',
    fixed: 'right',
  },
]
