export const columns = [
  {
    title: '#',
    type: 'number',
    width: '50px',
    fixed: 'left',
  },
  {
    key: 'type',
    title: '操作类型',
    align: 'center',
    minWidth: '100px',
    customSlot: 'type',
  },
  {
    key: 'userName',
    title: '操作人',
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'description',
    title: '操作描述',
    width: '160px',
    align: 'center',
    ellipsisTooltip: true,
  },
  {
    key: 'httpMethod',
    title: '请求方式',
    sort: true,
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'url',
    title: '请求地址',
    align: 'center',
    ellipsisTooltip: true,
  },
  {
    key: 'classPath',
    title: '类路径',
    align: 'center',
    ellipsisTooltip: true,
  },
  {
    key: 'spendTime',
    title: '消耗时间',
    minWidth: '100px',
    sort: true,
    align: 'center',
    customSlot: 'spendTime',
  },
  {
    key: 'os',
    title: '操作系统',
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'device',
    title: '设备名称',
    align: 'center',
    width: '180px',
    ellipsisTooltip: true,
  },
  {
    key: 'browser',
    title: '浏览器类型',
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'ip',
    title: 'ip',
    minWidth: '100px',
    align: 'center',
  },
  {
    key: 'createTime',
    title: '操作时间',
    sort: true,
    width: '180px',
    align: 'center',
  },
  {
    key: 'operator',
    title: '操作',
    width: '80px',
    align: 'center',
    customSlot: 'operator',
    fixed: 'right',
  },
]
