export const columns = [
  {
    title: '',
    type: 'checkbox',
    width: '50px',
    fixed: 'left',
  },
  {
    title: '#',
    type: 'number',
    width: '50px',
    fixed: 'left',
  },
  {
    key: 'avatar',
    title: '头像',
    width: '80px',
    align: 'center',
    hide: true,
    customSlot: 'avatar',
  },
  {
    key: 'username',
    title: '用户名',
    minWidth: '140px',
    align: 'center',
  },
  {
    key: 'account',
    title: '账号',
    minWidth: '140px',
    align: 'center',
  },
  {
    key: 'roles',
    title: '角色',
    align: 'center',
    minWidth: '140px',
    customSlot: 'roles',
  },
  {
    key: 'sex',
    title: '性别',
    sort: true,
    align: 'center',
    width: '100px',
    customSlot: 'sex',
  },
  {
    key: 'email',
    title: '邮箱',
    minWidth: '140px',
    align: 'center',
  },
  {
    key: 'mobile',
    title: '手机号',
    minWidth: '140px',
    align: 'center',
  },
  {
    key: 'birthday',
    title: '生日',
    hide: true,
    width: '160px',
    align: 'center',
  },
  {
    key: 'state',
    title: '状态',
    sort: true,
    width: '100px',
    align: 'center',
    customSlot: 'state',
  },
  {
    key: 'createTime',
    title: '注册时间',
    width: '180px',
    sort: true,
    align: 'center',
  },
  {
    key: 'operator',
    title: '操作',
    align: 'center',
    width: '180px',
    customSlot: 'operator',
    fixed: 'right',
  },
]
